# Generated by Django 4.2.1 on 2023-05-28 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_usertype_profile_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userType',
        ),
    ]
