# Generated by Django 4.2.1 on 2023-05-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
