# Generated by Django 4.2.1 on 2023-05-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fechaLimite',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
