# Generated by Django 4.2.1 on 2023-06-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_fechalimite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_donante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_paciente',
            field=models.BooleanField(default=False),
        ),
    ]
