# Generated by Django 4.2.1 on 2023-06-14 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_is_donante_profile_is_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_paciente',
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paciente', models.BooleanField(default=False)),
                ('idProfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
