# Generated by Django 4.2.1 on 2023-06-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_is_paciente_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='idProfile',
            new_name='profile',
        ),
    ]
