# Generated by Django 4.2.1 on 2023-06-14 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_rename_idprofile_paciente_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='profile',
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
