# Generated by Django 4.2.1 on 2023-06-17 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_alter_paciente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSangre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('U', 'No Informa'), ('N', 'No Binario')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipoDNI',
            field=models.CharField(choices=[('DNI', 'DNI'), ('LE', 'LE'), ('LC', 'LC')], default='DNI', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipoSangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('0+', '0+'), ('0-', '0-'), ('B+', 'B+'), ('AB+', 'AB+')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tiposSangre',
            field=models.ManyToManyField(related_name='sangrePacientes', to='users.tiposangre'),
        ),
    ]
