# Generated by Django 4.2.1 on 2023-06-24 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instituciones', '0001_initial'),
        ('users', '0013_paciente_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fechaLimite',
        ),
        migrations.AddField(
            model_name='paciente',
            name='cantidadDonantes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instituciones.ciudad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='comentario',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fechaLimite',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instituciones.instituciones'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
