# Generated by Django 4.2.1 on 2023-06-25 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instituciones', '0001_initial'),
        ('users', '0014_remove_profile_fechalimite_paciente_cantidaddonantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instituciones.instituciones'),
        ),
        migrations.CreateModel(
            name='PacienteInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucionPaciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Instituciones.instituciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paciente')),
            ],
        ),
    ]
