# Generated by Django 4.2.1 on 2023-06-25 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instituciones', '0001_initial'),
        ('users', '0015_alter_paciente_institucion_pacienteinstitucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instituciones.instituciones'),
        ),
    ]
