# Generated by Django 4.2.1 on 2023-06-26 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_paciente_institucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadDonantes', models.IntegerField(null=True)),
                ('mail', models.CharField(max_length=255, null=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.paciente')),
            ],
        ),
    ]
