# Generated by Django 4.2.1 on 2023-06-26 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_pacienteinstitucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteinstitucion',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.paciente'),
        ),
    ]
