# Generated by Django 4.2.1 on 2023-06-26 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_pacienteinstitucion_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacienteinstitucion',
            name='paciente',
        ),
        migrations.AddField(
            model_name='pacienteinstitucion',
            name='Paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.paciente'),
        ),
    ]
