# Generated by Django 4.2.1 on 2023-06-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_pacienteinstitucion_paciente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacienteinstitucion',
            old_name='Paciente',
            new_name='paciente',
        ),
    ]
