# Generated by Django 4.2.1 on 2023-06-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_paciente_pacienteinstitucion_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='cantidadDonantes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='mail',
        ),
    ]
