# Generated by Django 4.2.1 on 2023-06-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_paciente_created_at_paciente_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='completo',
        ),
        migrations.AddField(
            model_name='pacienteinstitucion',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
