# Generated by Django 4.2.1 on 2023-06-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_paciente_completo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fechaLimite',
        ),
        migrations.AddField(
            model_name='pacienteinstitucion',
            name='comentario',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='pacienteinstitucion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='pacienteinstitucion',
            name='fechaLimite',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pacienteinstitucion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated at'),
        ),
    ]
