# Generated by Django 4.2.1 on 2023-06-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_paciente_comentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='tiposSangre',
        ),
        migrations.AddField(
            model_name='pacienteinstitucion',
            name='tiposSangre',
            field=models.ManyToManyField(related_name='sangrePacientes', to='users.tiposangre'),
        ),
    ]
