# Generated by Django 4.2.1 on 2023-07-05 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instituciones', '0001_initial'),
        ('users', '0026_remove_paciente_tipossangre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='institucion',
        ),
        migrations.AddField(
            model_name='pacienteinstitucion',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instituciones.instituciones'),
        ),
        migrations.AlterField(
            model_name='pacienteinstitucion',
            name='completo',
            field=models.BooleanField(default=True),
        ),
    ]
