# Generated by Django 4.2.1 on 2023-07-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_paciente_institucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteinstitucion',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
