# Generated by Django 4.2.3 on 2023-07-10 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_pacienteinstitucion_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReposicionElegida', models.DateField()),
                ('comentario', models.TextField(blank=True, max_length=1024, null=True)),
                ('confirmacionAsistencia', models.BooleanField(default=False)),
                ('fechaConfirmacionAsistencia', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='donantes',
            field=models.ManyToManyField(related_name='donantes', to='users.donantes'),
        ),
    ]
