# Generated by Django 4.2.3 on 2023-07-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_donantes_paciente_donantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donantes',
            old_name='fechaReposicionElegida',
            new_name='fechaDonancionElegida',
        ),
        migrations.AddField(
            model_name='donantes',
            name='tipoSangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('0+', '0+'), ('0-', '0-'), ('B+', 'B+'), ('AB+', 'AB+')], max_length=255, null=True),
        ),
    ]
