# Generated by Django 4.2.3 on 2023-07-11 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0031_remove_donantes_fechaconfirmacionasistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donantes',
            name='userProfile',
        ),
        migrations.AddField(
            model_name='donantes',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
