# Generated by Django 4.2.3 on 2023-07-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_donantes_userprofile_donantes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='donantes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_donante',
        ),
        migrations.AddField(
            model_name='donantes',
            name='is_donante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donantes',
            name='paciente',
            field=models.ManyToManyField(related_name='donantes', to='users.paciente'),
        ),
    ]
