# Generated by Django 4.2.3 on 2023-07-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_paciente_donantes_remove_profile_is_donante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donantes',
            name='is_donante',
        ),
        migrations.RemoveField(
            model_name='donantes',
            name='paciente',
        ),
        migrations.AddField(
            model_name='donantes',
            name='pacienteInstitucion',
            field=models.ManyToManyField(related_name='donantes', to='users.pacienteinstitucion'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_donante',
            field=models.BooleanField(default=False),
        ),
    ]
