# Generated by Django 4.2.3 on 2023-07-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_donantes_is_donante_remove_donantes_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_donante',
        ),
        migrations.AddField(
            model_name='donantes',
            name='is_donante',
            field=models.BooleanField(default=False),
        ),
    ]
