# Generated by Django 4.2.3 on 2023-07-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_profile_is_donante_donantes_is_donante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donantes',
            name='pacienteInstitucion',
        ),
    ]
