# Generated by Django 4.2.3 on 2023-08-21 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0037_donantes_pacienteinstitucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donantes',
            name='user',
        ),
        migrations.AddField(
            model_name='donantes',
            name='user',
            field=models.ManyToManyField(related_name='UsuarioDonante', to=settings.AUTH_USER_MODEL),
        ),
    ]
