# Generated by Django 4.2.1 on 2023-05-17 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=255)),
                ('codigoPostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProvincia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreInstitucion', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('idCiudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instituciones.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='idProvincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instituciones.provincia'),
        ),
    ]
